# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

dist: xenial  # Ubuntu 16.04

env:
  global:
    - CODACY_PROJECT_TOKEN=aaaabbbcddddfffffhhhhh  #  TBA according created project

language: python

sudo: false

python:
  # - 2.7
  - 3.5
  - 3.6
  - 3.7

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

before_install:
  - pip install --upgrade pip

install:
  - pip install Cython  # required by pycocotools
  - pip install -r requirements.txt
  - pip install "nose>=1.3.7" coverage codecov "pytest>=3.0.5" pytest-cov codacy-coverage check-manifest flake8
  - pip list

before_script:
  - gcc --version ; python --version ; pip --version ; pwd ; ls -l
  - # check-manifest
  - python setup.py check -m -s

script:
  - coverage run --source imageai -m py.test imageai -v --doctest-modules
  # - flake8 . --ignore=E402,E731 --max-line-length=100
  - python setup.py install

after_success:
  - codecov  # public repository on Travis CI
  - coverage xml
  # - python-codacy-coverage -r coverage.xml
  - coverage report
